name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_docker_image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SERVER_OUTPUT_PATH: ${{ secrets.SERVER_OUTPUT_PATH }}
    steps:
    - name: Setup Private Key
      run: |
        mkdir -p ~/.ssh/
        echo "$SERVER_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build docker image
      run: |
        ./start.sh
        if [ ! -d ".tmp" ]; then
          exit 1
        fi

    - name: push image to server
      if: success()
      run: |
        export PROJECT_PATH=$PWD
        IMAGE_NAME="esp-hmi"
        IMAGE_VERSION="1.0.0"
        if [[ "$(sudo docker images -q "${IMAGE_NAME}:${IMAGE_VERSION}" 2> /dev/null)" == "" ]]; then
          exit 1
        else
          sudo docker save $(sudo docker images -q "${IMAGE_NAME}:${IMAGE_VERSION}" 2> /dev/null) > ${PROJECT_PATH}/tools/esp-hmi.tar
        fi
        cd ..
        tar zcvf esp-hmi.tar.gz esp-hmi
        scp -P $SERVER_PORT esp-hmi.tar.gz $SERVER_USER@$SERVER_HOST:$SERVER_OUTPUT_PATH
        